export const TOKENS = {
  color: {
    bg:          "var(--color-bg)",
    surface:     "var(--color-surface)",
    surfaceAlt:  "var(--color-surface-alt)",
    overlay:     "var(--color-overlay)",
    border:      "var(--color-border)",
    borderFocus: "var(--color-border-focus)",
    textPrimary:   "var(--color-text-primary)",
    textSecondary: "var(--color-text-secondary)",
    textMuted:     "var(--color-text-muted)",
    textInverse:   "var(--color-text-inverse)",
    accent:        "var(--color-accent)",
    accentHover:   "var(--color-accent-hover)",
    accentLight:   "var(--color-accent-light)",
    accentMuted:   "var(--color-accent-muted)",
    success: "var(--color-success)",
    error:   "var(--color-error)",
    warning: "var(--color-warning)",
  },
  font: {
    sans: "Inter, system-ui, sans-serif",
    mono: "'DM Mono', ui-monospace, monospace",
  },
  fontSize: {
    xs:   "11px",
    sm:   "13px",
    base: "15px",
    md:   "17px",
    lg:   "20px",
    xl:   "24px",
    "2xl":"30px",
    "3xl":"38px",
  },
  fontWeight: {
    regular: 400,
    medium:  500,
    semibold:600,
    bold:    700,
  },
  lineHeight: {
    tight:  1.2,
    snug:   1.4,
    normal: 1.6,
    loose:  1.8,
  },
  letterSpacing: {
    tight:  "-0.02em",
    normal: "0em",
    wide:   "0.04em",
    wider:  "0.08em",
    widest: "0.14em",
  },
  space: {
    "1": "4px",  "2": "8px",  "3": "12px", "4": "16px",
    "5": "20px", "6": "24px", "7": "28px", "8": "32px",
    "10":"40px", "12":"48px", "14":"56px", "16":"64px",
    "20":"80px", "24":"96px",
  },
  radius: {
    sm:   "6px",
    md:   "10px",
    lg:   "16px",
    xl:   "22px",
    full: "9999px",
  },
  shadow: {
    xs:    "0 1px 2px rgba(0,0,0,0.4)",
    sm:    "0 2px 6px rgba(0,0,0,0.5)",
    md:    "0 4px 16px rgba(0,0,0,0.55)",
    lg:    "0 8px 32px rgba(0,0,0,0.6)",
    xl:    "0 16px 48px rgba(0,0,0,0.7)",
    focus: "0 0 0 3px rgba(201,168,76,0.32)",
  },
  duration: {
    fast:   "120ms",
    normal: "200ms",
    slow:   "340ms",
  },
  easing: {
    smooth: "cubic-bezier(0.4,0,0.2,1)",
    spring: "cubic-bezier(0.34,1.56,0.64,1)",
    out:    "cubic-bezier(0,0,0.2,1)",
  },
}

export const T = TOKENS
